#!/usr/bin/env node
/**
 * ts-candidates 扫描脚本.
 *
 * 按机械规则分类 .js .jsx .mjs .cjs 文件, 输出"建议转 TS"清单.
 * 详细规则见同目录 SKILL.md 的 4 条优先级规则.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, basename, extname, dirname } from 'node:path';

const REPO = execFileSync('git', ['rev-parse', '--show-toplevel'], {
  cwd: import.meta.dirname,
  encoding: 'utf8',
}).trim();

const SKIP_DIRS = new Set([
  'node_modules', '.next', 'out', 'out-rtl', 'dist', 'build',
  '.git', '.turbo', 'coverage', 'public', 'reports',
]);

const SKIP_PATH_FRAGMENTS = ['/apps-icons/'];

const EXTS = ['.js', '.jsx', '.mjs', '.cjs'];

const CONFIG_NAME_PATTERNS = [
  /^.+\.config\.(?:js|mjs)$/,
  /^analyze\.js$/,
  /^\.commitlintrc\.js$/,
  /^\.lintstagedrc\.js$/,
  /^\.eslintrc\.js$/,
];

const VENDOR_SDK_NAMES = new Set(['gt4.js', 'charting_library.esm.js']);

const CHART_ADAPTER_LOW_VALUE = new Set([
  'packages/apps-kit/components/chart/k-chart/lib/trading-view/library/save_load_adapter.js',
  'packages/apps-kit/components/chart/k-chart/lib/trading-view/library/time-zome.js',
]);

const GENERATED_RE = /^\s*(?:\/\/|\/\*|\*)[^\n]{0,200}(?:code generated|@generated|auto[-\s]?generated|generated by)/i;

function* walkFiles(root) {
  const stack = [root];
  while (stack.length) {
    const cur = stack.pop();
    let entries;
    try {
      entries = readdirSync(cur, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      const full = join(cur, e.name);
      if (e.isDirectory()) {
        if (SKIP_DIRS.has(e.name)) continue;
        if (SKIP_PATH_FRAGMENTS.some((f) => full.includes(f))) continue;
        stack.push(full);
      } else if (e.isFile()) {
        if (!EXTS.some((x) => e.name.endsWith(x))) continue;
        yield full;
      }
    }
  }
}

function classify(fp, content, lineCount, size) {
  const rel = fp.slice(REPO.length + 1);
  const name = basename(fp);
  const ext = extname(fp);
  const firstLine = (content.split('\n', 1)[0] || '').slice(0, 300);

  // 陷阱 #7: credential 必须最优先，避免含敏感字段的文件因路径含 `/scripts/` 先命中 node-script
  if (/(client_secret|access_token|refresh_token|private_key)\s*[:=]/.test(content)) {
    return { tag: 'credential', cat: 'no' };
  }

  // i18n-data 必须早于 generated / minified-vendor
  if (/\/i18n\/src\/meta\/[^/]+\/[^/]+\.js$/.test(fp)) {
    return { tag: 'i18n-data', cat: 'no' };
  }

  // 规则 1: 不应转
  if (ext === '.cjs') return { tag: 'config', cat: 'no' };
  if (ext === '.mjs' && /\.config\.mjs$/.test(name)) return { tag: 'config', cat: 'no' };
  if (CONFIG_NAME_PATTERNS.some((re) => re.test(name))) return { tag: 'config', cat: 'no' };
  if (rel.includes('/plugin/babel-plugin-')) return { tag: 'babel-plugin', cat: 'no' };
  if (rel.startsWith('packages/apps-base-kline/')) return { tag: 'kline-pkg', cat: 'no' };
  if (rel.startsWith('scripts/') || rel.includes('/scripts/')) return { tag: 'node-script', cat: 'no' };
  if (/^apps\/[^/]+\/server\.js$/.test(rel)) return { tag: 'next-server', cat: 'no' };
  if (GENERATED_RE.test(firstLine)) return { tag: 'generated', cat: 'no' };
  if (lineCount === 1 && size > 5000) return { tag: 'minified-vendor', cat: 'no' };
  if (VENDOR_SDK_NAMES.has(name)) return { tag: 'vendor-sdk', cat: 'no' };

  // 规则 2: 不建议转
  if (lineCount <= 6) {
    const nonEmpty = content.split('\n').filter((l) => l.trim());
    if (nonEmpty.length > 0 && nonEmpty.every((l) => /^export\s*\{[^}]+\}\s*from/.test(l.trim()))) {
      return { tag: 'barrel-only', cat: 'low' };
    }
  }
  if (/^export const \w+ = `/m.test(content) || /^module\.exports = `/m.test(content)) {
    if (!/\bfunction\b|\bclass\s+\w+|=>|\bif\s*\(|\bfor\s*\(|\bwhile\s*\(/.test(content)) {
      return { tag: 'string-template', cat: 'low' };
    }
  }
  const dataFirstLine = /^(?:module\.exports = \{|const \w+ = \{|export const \w+ = \{)/.test(firstLine);
  if (dataFirstLine && !/\bfunction\b|\bclass\s+\w+|=>|\breturn\s/.test(content)) {
    return { tag: 'data-only', cat: 'low' };
  }

  // 规则 3: 建议转
  if (ext === '.jsx') {
    const dir = dirname(fp);
    try {
      const siblings = readdirSync(dir);
      if (siblings.some((s) => s.endsWith('.tsx'))) {
        return { tag: 'jsx-mixed', cat: 'yes' };
      }
    } catch {
      // ignore
    }
  }
  // 陷阱 #5: chart-adapter 不能依赖首行 import (该目录下文件首行常为 /** 注释)
  // 改为纯路径判定; 真 vendor (charting_library.esm.js 等) 已被 VENDOR_SDK_NAMES 提前排除
  if (rel.includes('/chart/k-chart/lib/') && !rel.includes('/vendor/')) {
    if (CHART_ADAPTER_LOW_VALUE.has(rel)) {
      return { tag: 'chart-low-value', cat: 'low' };
    }
    return { tag: 'chart-adapter', cat: 'yes' };
  }
  const classMatches = (content.match(/\bclass\s+\w+/g) || []).length;
  const functionMatches = (content.match(/\bfunction\s+\w+/g) || []).length;
  if (classMatches + functionMatches >= 3) {
    return { tag: 'logic-code', cat: 'yes' };
  }

  // 规则 4: 默认
  return { tag: 'gray-area', cat: 'gray' };
}

function gitMeta() {
  const run = (...args) => {
    try {
      return execFileSync('git', ['-C', REPO, ...args], {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      }).trim();
    } catch {
      return '';
    }
  };
  return {
    branch: run('branch', '--show-current') || '?',
    short: run('rev-parse', '--short=10', 'HEAD') || '?',
    worktree: !run('status', '--porcelain') ? 'clean' : 'dirty',
    lastMsg: run('log', '-1', '--pretty=%s'),
  };
}

function todayIso() {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function findIndependent() {
  try {
    const r = execFileSync(
      'find',
      [
        REPO,
        '(',
        '-name', 'node_modules', '-o',
        '-name', '.next', '-o',
        '-name', 'out', '-o',
        '-name', 'out-rtl', '-o',
        '-name', 'dist', '-o',
        '-name', 'build', '-o',
        '-name', '.git', '-o',
        '-name', '.turbo', '-o',
        '-name', 'coverage', '-o',
        '-name', 'public', '-o',
        '-name', 'reports', '-o',
        '-path', '*/apps-icons/*',
        ')', '-prune',
        '-o',
        '-type', 'f',
        '(',
        '-name', '*.js', '-o',
        '-name', '*.jsx', '-o',
        '-name', '*.mjs', '-o',
        '-name', '*.cjs',
        ')', '-print',
      ],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], maxBuffer: 50 * 1024 * 1024 }
    );
    return r.split('\n').filter((l) => l).length;
  } catch {
    return -1;
  }
}

function main() {
  const all = [];
  for (const fp of walkFiles(REPO)) {
    let content;
    try {
      content = readFileSync(fp, 'utf8');
    } catch {
      continue;
    }
    let stat;
    try {
      stat = statSync(fp);
    } catch {
      continue;
    }
    const lineCount = content.split('\n').length;
    const cls = classify(fp, content, lineCount, stat.size);
    all.push({
      file: fp.slice(REPO.length + 1),
      lines: lineCount,
      tag: cls.tag,
      cat: cls.cat,
    });
  }

  const byTag = new Map();
  for (const e of all) {
    if (!byTag.has(e.tag)) byTag.set(e.tag, []);
    byTag.get(e.tag).push(e);
  }

  const yesEntries = all.filter((e) => e.cat === 'yes');
  const yesByTag = new Map();
  for (const e of yesEntries) {
    if (!yesByTag.has(e.tag)) yesByTag.set(e.tag, []);
    yesByTag.get(e.tag).push(e);
  }
  for (const [, list] of yesByTag) {
    list.sort((a, b) => (a.file < b.file ? -1 : 1));
  }

  const meta = gitMeta();
  const out = [];

  out.push('# 可 TS 化清单');
  out.push('');
  out.push(`- 统计日期: ${todayIso()}`);
  out.push(`- 分支: \`${meta.branch}\``);
  out.push(`- Commit: \`${meta.short}\` — ${meta.lastMsg}`);
  out.push(`- 工作树: ${meta.worktree}`);
  out.push(`- 扫描的 .js/.jsx/.mjs/.cjs 总数: **${all.length}**`);
  out.push(`- 共 **${yesEntries.length}** 个文件建议转 TS`);
  out.push('');

  out.push('## 准确性核验');
  out.push('');
  const findCount = findIndependent();
  const ok = all.length === findCount ? '✓' : '**✗ 不一致**';
  out.push('| 锚点 | 主统计 | system find | 一致 |');
  out.push('|------|------:|-----------:|:----:|');
  out.push(`| 候选文件总数 | ${all.length} | ${findCount} | ${ok} |`);
  out.push('');

  const sectionTitles = {
    'jsx-mixed': 'jsx → tsx',
    'chart-adapter': 'chart 适配器',
    'logic-code': '业务逻辑',
  };
  for (const tag of ['jsx-mixed', 'chart-adapter', 'logic-code']) {
    const list = yesByTag.get(tag) || [];
    out.push(`## ${sectionTitles[tag]} (${list.length})`);
    out.push('');
    if (list.length === 0) {
      out.push('（无）');
    } else {
      for (const e of list) {
        out.push(`- \`${e.file}\` (${e.lines} 行)`);
      }
    }
    out.push('');
  }

  out.push('## 分类分布 (内部 debug)');
  out.push('');
  out.push('| 标签 | 数量 | 类别 |');
  out.push('|------|----:|------|');
  const catLabel = { yes: '建议转', no: '不应转', low: '不建议转', gray: '灰色地带' };
  const tagsSorted = [...byTag.entries()].sort((a, b) => {
    if (b[1].length !== a[1].length) return b[1].length - a[1].length;
    return a[0] < b[0] ? -1 : 1;
  });
  for (const [tag, list] of tagsSorted) {
    out.push(`| \`${tag}\` | ${list.length} | ${catLabel[list[0].cat]} |`);
  }
  out.push('');

  process.stdout.write(out.join('\n') + '\n');
}

main();
